### ISSUE TITLE
adium locks up

### ISSUE THREAD

**Issue by josephmc5** [alampros/markium#4]
Adium 1.5.6 seems to lock out when installed. I'm thinking about picking this up. This would be really cool to have working.

**Comment by waddles** [comment]
I have the same problem. Sometimes it gets as far as displaying my buddies and all members of the group chat, then for each message in the chat history, I get a line saying

```
/path/to/markium.AdiumPlugin/Contents/Resources/redcarpet_w.rb:10:in `markdown':
 undefined method `new' for Redcarpet:Module (NoMethodError) from 
/path/to/markium.AdiumPlugin/Contents/Resources/redcarpet_w.rb:22:in `

'
```
However, running `ruby markium/redcarpet_w.rb README.md` from within the repo will correctly render the markdown text.

```
/usr/bin/ruby --version
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]

gem list

*** LOCAL GEMS ***

albino (1.3.3)
bigdecimal (1.2.0)
CFPropertyList (2.2.8)
io-console (0.4.2)
json (1.7.7)
libxml-ruby (2.6.0)
mini_portile (0.6.2)
minitest (4.3.2)
nokogiri (1.6.6.2, 1.5.6)
posix-spawn (0.3.9)
psych (2.0.0)
pygments.rb (0.6.2)
rake (0.9.6)
rdoc (4.0.0)
redcarpet (3.2.2)
sqlite3 (1.3.7)
test-unit (2.0.0.0)
yajl-ruby (1.2.1)
```

**Comment by waddles** [comment]
Well, I found it's partly due to a packaging error. The version of redcarpet_w.rb that gets installed into `~/Library/Application\ Support/Adium\ 2.0/Plugins/markium.AdiumPlugin/Contents/Resources/redcarpet_w.rb` is not the same as the version in the repo at `markium/redcarpet_w.rb`

Replacing that file with the version in the repo gets rid of the error messages above but does not prevent the hangs.

**Comment by waddles** [comment]
Clearing all logs and starting Adium with no previous sessions open gets it to start normally, but as I start joining jabber chats, I find it locks up again, as if it's trying to request history and re-render the whole lot instead of only render new incoming messages. This plugin probably works fine for IRC chats, but not jabber/XMPP.
